#!/usr/bin/env bash
set -euxo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GRAMMAR="$SCRIPT_DIR/Spec.g4"

command -v antlr4 >/dev/null || {
  echo "Error: antlr4 not found in PATH" >&2
  exit 1
}

antlr4 -Dlanguage=Python3 -visitor -no-listener -lib "$SCRIPT_DIR" "$GRAMMAR" -o "$SCRIPT_DIR"

# Cleanup & rename
rm -f "$SCRIPT_DIR"/Spec*.interp "$SCRIPT_DIR"/Spec*.tokens

declare -A rename_map=(
  ["SpecLexer.py"]="spec_lexer.py"
  ["SpecParser.py"]="spec_parser.py"
  ["SpecVisitor.py"]="spec_visitor.py"
)

for orig in "${!rename_map[@]}"; do
  mv "$SCRIPT_DIR/$orig" "$SCRIPT_DIR/${rename_map[$orig]}"
done

# Remove abolute path from autogenerated comment
for f in "$SCRIPT_DIR"/spec_*.py; do
  sed -i 's|# Generated from .*/\(Spec\.g4\)|\# Generated from \1|' "$f"
done

# Fix imports in spec_visitor.py
sed -i \
  -e 's/from \.SpecParser import/from .spec_parser import/' \
  -e 's/from SpecParser import/from spec_parser import/' \
  "$SCRIPT_DIR/spec_visitor.py"
